module.exports.schema = [
  {
    name: "version",
    mode: "NULLABLE",
    type: "INTEGER",
    description: null,
  },
  {
    name: "fulfillments",
    mode: "REPEATED",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "state",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "type",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "uid",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
    ],
  },
  {
    name: "netAmounts",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "serviceChargeMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "tipMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "discountMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "taxMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "totalMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
    ],
  },
  {
    name: "totalServiceChargeMoney",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "currency",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "amount",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
    ],
  },
  {
    name: "netAmountDueMoney",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "currency",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "amount",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
    ],
  },
  {
    name: "customerId",
    mode: "NULLABLE",
    type: "STRING",
    description: null,
  },
  {
    name: "refunds",
    mode: "REPEATED",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "status",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "processingFeeMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "tenderId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "reason",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "locationId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "createdAt",
        mode: "NULLABLE",
        type: "TIMESTAMP",
        description: null,
      },
      {
        name: "amountMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "transactionId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "id",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
    ],
  },
  {
    name: "discounts",
    mode: "REPEATED",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "appliedMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "percentage",
        mode: "NULLABLE",
        type: "FLOAT",
        description: null,
      },
      {
        name: "catalogObjectId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "type",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "name",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "scope",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "catalogVersion",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
      {
        name: "amountMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "uid",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
    ],
  },
  {
    name: "ticketName",
    mode: "NULLABLE",
    type: "STRING",
    description: null,
  },
  {
    name: "totalDiscountMoney",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "currency",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "amount",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
    ],
  },
  {
    name: "tenders",
    mode: "REPEATED",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "cardDetails",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "entryMethod",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "card",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "bin",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
              {
                name: "prepaidType",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "cardType",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "cardBrand",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "last4",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
              {
                name: "expYear",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
              {
                name: "fingerprint",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "expMonth",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "status",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
        ],
      },
      {
        name: "cashDetails",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "changeBackMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
                fields: [],
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
                fields: [],
              },
            ],
          },
          {
            name: "buyerTenderedMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
                fields: [],
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
                fields: [],
              },
            ],
          },
        ],
      },
      {
        name: "customerId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "processingFeeMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "paymentId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "tipMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "id",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "transactionId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "amountMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "type",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "createdAt",
        mode: "NULLABLE",
        type: "TIMESTAMP",
        description: null,
      },
      {
        name: "locationId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
    ],
  },
  {
    name: "source",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "name",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
    ],
  },
  {
    name: "locationId",
    mode: "NULLABLE",
    type: "STRING",
    description: null,
  },
  {
    name: "totalTaxMoney",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "currency",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "amount",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
    ],
  },
  {
    name: "state",
    mode: "NULLABLE",
    type: "STRING",
    description: null,
  },
  {
    name: "taxes",
    mode: "REPEATED",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "appliedMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "percentage",
        mode: "NULLABLE",
        type: "FLOAT",
        description: null,
      },
      {
        name: "catalogObjectId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "type",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "name",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "scope",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "catalogVersion",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
      {
        name: "uid",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
    ],
  },
  {
    name: "totalMoney",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "currency",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "amount",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
    ],
  },
  {
    name: "closedAt",
    mode: "NULLABLE",
    type: "TIMESTAMP",
    description: null,
  },
  {
    name: "returnAmounts",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "serviceChargeMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "tipMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "discountMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "taxMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "totalMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
    ],
  },
  {
    name: "updatedAt",
    mode: "NULLABLE",
    type: "TIMESTAMP",
    description: null,
  },
  {
    name: "totalTipMoney",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "currency",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "amount",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
    ],
  },
  {
    name: "returns",
    mode: "REPEATED",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "returnDiscounts",
        mode: "REPEATED",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "appliedMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "percentage",
            mode: "NULLABLE",
            type: "FLOAT",
            description: null,
          },
          {
            name: "catalogObjectId",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "type",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "name",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "scope",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "catalogVersion",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
          {
            name: "uid",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
        ],
      },
      {
        name: "returnTaxes",
        mode: "REPEATED",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "appliedMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "percentage",
            mode: "NULLABLE",
            type: "FLOAT",
            description: null,
          },
          {
            name: "catalogObjectId",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "type",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "name",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "scope",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "catalogVersion",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
          {
            name: "uid",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
        ],
      },
      {
        name: "returnLineItems",
        mode: "REPEATED",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "note",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "returnModifiers",
            mode: "REPEATED",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "totalPriceMoney",
                mode: "NULLABLE",
                type: "RECORD",
                description: null,
                fields: [
                  {
                    name: "currency",
                    mode: "NULLABLE",
                    type: "STRING",
                    description: null,
                  },
                  {
                    name: "amount",
                    mode: "NULLABLE",
                    type: "INTEGER",
                    description: null,
                  },
                ],
              },
              {
                name: "uid",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "basePriceMoney",
                mode: "NULLABLE",
                type: "RECORD",
                description: null,
                fields: [
                  {
                    name: "currency",
                    mode: "NULLABLE",
                    type: "STRING",
                    description: null,
                  },
                  {
                    name: "amount",
                    mode: "NULLABLE",
                    type: "INTEGER",
                    description: null,
                  },
                ],
              },
              {
                name: "name",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "catalogObjectId",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "catalogVersion",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "totalMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "totalDiscountMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "totalTaxMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "appliedDiscounts",
            mode: "REPEATED",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "appliedMoney",
                mode: "NULLABLE",
                type: "RECORD",
                description: null,
                fields: [
                  {
                    name: "currency",
                    mode: "NULLABLE",
                    type: "STRING",
                    description: null,
                  },
                  {
                    name: "amount",
                    mode: "NULLABLE",
                    type: "INTEGER",
                    description: null,
                  },
                ],
              },
              {
                name: "discountUid",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "uid",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
            ],
          },
          {
            name: "grossReturnMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "variationTotalPriceMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "name",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "itemType",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "variationName",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "appliedTaxes",
            mode: "REPEATED",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "appliedMoney",
                mode: "NULLABLE",
                type: "RECORD",
                description: null,
                fields: [
                  {
                    name: "currency",
                    mode: "NULLABLE",
                    type: "STRING",
                    description: null,
                  },
                  {
                    name: "amount",
                    mode: "NULLABLE",
                    type: "INTEGER",
                    description: null,
                  },
                ],
              },
              {
                name: "taxUid",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "uid",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
            ],
          },
          {
            name: "sourceLineItemUid",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "catalogVersion",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
          {
            name: "catalogObjectId",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "quantity",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
          {
            name: "basePriceMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "uid",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
        ],
      },
      {
        name: "sourceOrderId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
    ],
  },
  {
    name: "createdAt",
    mode: "NULLABLE",
    type: "TIMESTAMP",
    description: null,
  },
  {
    name: "lineItems",
    mode: "REPEATED",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "pricingBlocklists",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "blockedTaxes",
            mode: "REPEATED",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "taxCatalogObjectId",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "uid",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
            ],
          },
          {
            name: "blockedDiscounts",
            mode: "REPEATED",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "discountCatalogObjectId",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "uid",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
            ],
          },
        ],
      },
      {
        name: "note",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "appliedDiscounts",
        mode: "REPEATED",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "appliedMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "discountUid",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "uid",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
        ],
      },
      {
        name: "totalMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "totalDiscountMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "totalTaxMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "variationTotalPriceMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "name",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "itemType",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "variationName",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "modifiers",
        mode: "REPEATED",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "name",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "catalogObjectId",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "totalPriceMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "quantity",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
          {
            name: "catalogVersion",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
          {
            name: "basePriceMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "uid",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
        ],
      },
      {
        name: "catalogObjectId",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
      {
        name: "grossSalesMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "appliedTaxes",
        mode: "REPEATED",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "appliedMoney",
            mode: "NULLABLE",
            type: "RECORD",
            description: null,
            fields: [
              {
                name: "currency",
                mode: "NULLABLE",
                type: "STRING",
                description: null,
              },
              {
                name: "amount",
                mode: "NULLABLE",
                type: "INTEGER",
                description: null,
              },
            ],
          },
          {
            name: "taxUid",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "uid",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
        ],
      },
      {
        name: "catalogVersion",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
      {
        name: "quantity",
        mode: "NULLABLE",
        type: "INTEGER",
        description: null,
      },
      {
        name: "basePriceMoney",
        mode: "NULLABLE",
        type: "RECORD",
        description: null,
        fields: [
          {
            name: "currency",
            mode: "NULLABLE",
            type: "STRING",
            description: null,
          },
          {
            name: "amount",
            mode: "NULLABLE",
            type: "INTEGER",
            description: null,
          },
        ],
      },
      {
        name: "uid",
        mode: "NULLABLE",
        type: "STRING",
        description: null,
      },
    ],
  },
  {
    name: "pricingOptions",
    mode: "NULLABLE",
    type: "RECORD",
    description: null,
    fields: [
      {
        name: "autoApplyDiscounts",
        mode: "NULLABLE",
        type: "BOOLEAN",
        description: null,
      },
    ],
  },
  {
    name: "id",
    mode: "NULLABLE",
    type: "STRING",
    description: null,
  },
];
